### ISSUE TITLE
Cannot register lookups: No ajax_select LookupChannel named 'countries' is registered.

### ISSUE THREAD

**Issue by NaturalBornCamper** [crucialfelix/django-ajax-selects#279] opened 2020-10-18 20:19 UTC
I copy-pasted the code in the [docs (install section)](https://django-ajax-selects.readthedocs.io/en/latest/Install.html), specifically the lookup:

In myapp/lookup.py
```
@register('countries')
class CountryLookup(LookupChannel):
    model = Country

    def get_query(self, q, request):
        return self.model.objects.filter(name__icontains=q).order_by('name')[:50]

    def format_item_display(self, item):
        return u"<span class='tag'>%s</span>" % item.name
```

But I'm getting:

> No ajax_select LookupChannel named 'countries' is registered.

yet in the [docs](https://django-ajax-selects.readthedocs.io/en/latest/LookupChannel.html#lookups-py), it says: "If you are using Django >= 1.7 then all lookups.py in all of your apps will be automatically imported on startup." so anyone knows what went wrong? I'm using the latest 3.1 Django and trying to show the form on a frontend page (not in the admin)

I also tried to put in my form and views:
`register('countries')`
`register(CountryLookup)`

**Comment by Steckelfisch** [comment] 2020-10-21 19:48
I can reproduce in a strange way.
(version 1.9.0)
I have a channel configured in settings. (called 'foo' ). and a @register channel on the the same model with the name 'foo_bar'.

When i start up the server the channel 'foo_bar' is not found (like yoy describe above). Then i query 'foo', wich returns a result.
After the query on channel 'foo', the  channel 'foo_bar' starts to function properly.

**Comment by Steckelfisch** [comment] 2020-10-22 09:51
did some more testing.
I added a channel (via @register) on another model. That channel did not work before i issued a request on a 
(different) channel defined in settings.

**Comment by rsskg** [comment] 2020-10-25 05:29
May be lookup.py should be lookups.py?

**Comment by NaturalBornCamper** [comment] 2020-10-25 19:22
> May be lookup.py should be lookups.py?

In the docs it says "lookup.py" singular. I didn't try the plural form however, but I gave up since and removed that library since the dev was not answering, ended up coding my own.

**Comment by leogout** [comment] 2020-11-18 09:49
I am facing the same issue, and my file is called `lookups.py`. I have `django 2.2` and I am using the latest version of this library.

**Comment by leogout** [comment] 2020-11-18 10:00
All right I found the mistake... It is quite hard to find if you don't dig deep enough as the readme does not mention this at all !  
But the answer is quite simple. Just follow the installation instructions in https://django-ajax-selects.readthedocs.io/en/latest/
You have to register ajax_select in your installed apps and register its URL...

**Comment by crucialfelix** [comment] 2020-11-20 21:09
I could certainly make sure the complete minimal install instructions are
in the readme.

So was it that you didn't add it to settings installed apps?

**Comment by leogout** [comment] 2020-11-20 22:30
Registering the library in `INSTALLED_APPS` and in the `url.py`. Things which are quite obvious for any django package but they flew over my head because I went too fast. I just did what the README.md told me without stopping and thinking.

Here are the relevant parts of the documentation that mentions it :

_Add the app:_

```py
# settings.py
INSTALLED_APPS = (
    ...
    'ajax_select',  # <-   add the app
    ...
)
```
_Include the urls in your project:_

```py
# urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from ajax_select import urls as ajax_select_urls

admin.autodiscover()

urlpatterns = [

    # place it at whatever base url you like
    url(r'^ajax_select/', include(ajax_select_urls)),

    url(r'^admin/', include(admin.site.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
```

**Comment by crucialfelix** [comment] 2020-11-21 18:25
Thanks for the clear explanation. I will put it in the readme.  It should
definitely be there, clear and simple

**Comment by leogout** [comment] 2020-11-21 19:33
You're welcome, I have made a PR if you like. Have a nice day.

**Comment by crucialfelix** [comment] 2020-11-25 19:58
Closing as it sounds like the problem was found. I merged the change to the readme.

Thanks everyone

**Closed** 2020-11-25 19:57 UTC
