### ISSUE TITLE
Issue with wagtail fields after updating from 1.7 => 1.8

### ISSUE THREAD

**Issue by feargalWag** [crucialfelix/django-ajax-selects#291] opened 2022-03-02 21:58 UTC
After updating `django-ajax-selects` from 1.6 to 1.9 using an automated tool. We noticed that certain `RichTextFields` in the Wagtail admin started to become uneditable. After dialing back the upgrades it was found that the bug was introduced from 
1.7 => 1.8. I'm trying to get my hands on the diff between those releases so I can better understand what caused this, but it's not immediately obvious where that is. 

The following two errors also showed up in the console for content types that had this issue(not all of them did)

<img width="699" alt="image" src="https://user-images.githubusercontent.com/61435828/156456326-127f7b74-2551-410e-817a-819db1e6489e.png">

<img width="694" alt="image" src="https://user-images.githubusercontent.com/61435828/156456379-bf9d7153-34d7-49da-965d-7c301bd533d3.png">

If anyone else experienced this, the downgrade fixes this at least.

**Comment by crucialfelix** [comment] 2022-03-04 16:38
Sorry hard to figure out what is going on there.  Unexpected < might be that html tags are being parsed as js?  Or is it an error response from server that is expected to be JSON but is actually html?

**Comment by crucialfelix** [comment] 2023-12-06 15:29
Closing as I don't recognize anything in that call stack as being caused by this package. Thanks

**Closed by crucialfelix** 2023-12-06 15:29 UTC
