### ISSUE TITLE
Popup not closing

### ISSUE THREAD

**Issue by mrdrprofuroboros** [crucialfelix/django-ajax-selects#176] opened 2016-08-20 10:43 UTC
Using Django 1.10
Installed ajax-selects and everything works fine except that when I click +add in admin foreign key fields (or M2M key fields) I get the popup window, fill it, click save and it doesn't disappear, staying blank with
popup closing... in the head
it can be closed manually and finally it creates the foreign object, but doesn't link it to the one i was editing

UPD:
Downgrading to django 1.9 helped, everything works fine, popup closes

**Comment by crucialfelix** [comment] 2016-08-20 12:08
Duplicate of #174

**Closed by crucialfelix** 2016-08-20 12:08 UTC
